import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Content from '@/components/Content'

//text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className='font-misans '>
        <div className='text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900'>
          <div className='max-w-7xl min-h-screen mx-auto'>
            <div className='flex flex-col'>
              <div className=''>
                <Header></Header>
              </div>
              <div className=''>
                <Content>{props.children}</Content>
              </div>
              <div>
                <Footer></Footer>
              </div>
            </div>
          </div>
          
        </div>
      </body>
    </html>
  )
}
