import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

import { SnackbarProvider, closeSnackbar, closeButton } from '@/components/Snackbar'

//text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900

export default async function RootLayout({children}) {

  return (
    <html lang="en">
      <body className='font-misans'>
        <SnackbarProvider maxSnack={3} autoHideDuration={100000} anchorOrigin={{vertical: 'top', horizontal: 'center'}} action={closeButton}/>
        {children}
      </body>
    </html>
  )
}
